### ISSUE TITLE
Benchmark results

### ISSUE THREAD

**Issue by linhlpv** [OffDynamicsRL/off-dynamics-rl#1]
Hi @OffDynamicsRL ,

Thank you for your amazing work and congrats for your acceptance at NeurIPS 2024. 

Do you have benchmark results for the baselines in these datasets? 

Thank you so much.
Best,
Linh

**Comment by dmksjfl** [comment]
Hi, we only conducted experiments on some selected environments and datasets, as reported in the paper. It is very expensive to run all possible experiments. Please let me know if you need benchmark results that we reported in the paper.

**Comment by linhlpv** [comment]
Hi @dmksjfl ,

I have a copy of your paper. Thank you :D
