### ISSUE TITLE
Bosa implementation

### ISSUE THREAD

**Issue by linhlpv** [OffDynamicsRL/off-dynamics-rl#3]
Hi @OffDynamicsRL ,

I just found a bug in the implementation of BOSA.
https://github.com/OffDynamicsRL/off-dynamics-rl/blob/bfdf2b2ded15cccc818f1608e51a1cd6baa85239/algo/offline_offline/bosa.py#L290 

I think it could be torch.ones_like rather than zero as we are initializing a standard distribution as a prior. 

Could you please check it?

Thank you so much and have a good day.
Best,
Linh

**Comment by dmksjfl** [comment]
Hi, nice catch! It indeed should be ones_like, otherwise errors would occur when running bosa. This should be a bug when I clean the codes. When running experiments reported in the paper, we use ones_like for std_prior. Will fix that. Thank you!

**Comment by linhlpv** [comment]
Cool. I will close this issue as it's clear. Good night bro.
